# Generated by Django 4.2.30 on 2026-08-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='car_type',
            new_name='type',
        ),
    ]
